name: 'WeThinkCode_ Send Twist Webooks'
description: 'Call Twist Webhooks'
inputs:
    twist-url: 
      description: 'The Twist Webhooks URL to post to'
      required: true
    content:
        description: 'The content of the notification'
        required: true
branding:
    icon: 'wtc-logo.svg'
    color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.twist-url }}
    - ${{ inputs.content }}